### ISSUE TITLE
Command-Line issues with readchar syscall

### ISSUE THREAD

**Issue by jplanck** [TheThirdOne/rars#135]
There is an issue with readchar syscall. The readcall requires a newline to accept the character, and doesn't read the newline char itself.  Perhaps the terminal mode line buffering is misconfigured for readchar.

The following code always causes a runtime exception "Error in /home/jplanck/./riscv1.asm line 6: Runtime exception at 0x00400010: invalid char input (syscall 12)"

```
# read chars in a loop, echoing the integer value of each char read 
# stores the chars as as a string and print the string.
.text
	la	t0, str
	li	t1, '\n'

loop:
	li 	a7, 12
	ecall
	li 	a7, 1
	ecall
	sb 	a0, 0(t0)
	addi	t0, t0, 1
	bne	a0, t1, loop
	sb	x0, 0(t0)
	
	li 	a7, 4
	la	a0, str
	ecall
	li 	a7, 10
	ecall
.data
str: .space 20
```
Here is the runtime response when i type "1234".
java -jar ~/opt/riscv/rars/rars1_5.jar riscv1.asm nc
1234
49
Error in /home/jplanck/riscv1.asm line 6: Runtime exception at 0x00400010: invalid char input (syscall 12)

Simulation terminated due to errors.

Here is the output when I type a newline after each char.
java -jar ~/opt/riscv/rars/rars1_5.jar riscv1.asm nc
1
492
503
514
52
Error in /home/jplanck/riscv1.asm line 6: Runtime exception at 0x00400010: invalid char input (syscall 12)

Simulation terminated due to errors.

system info, 
Linux version 5.11.0-38-generic (buildd@lgw01-amd64-041) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021

**Comment by tarvlad** [comment]
I think i fixed it https://github.com/TheThirdOne/rars/pull/174

**Comment by tarvlad** [comment]
However, now if you call the line reading, the buffer will be reset. I can add when reading a line, reading the entire remaining line lying in the buffer (if it is there), if necessary

**Comment by jplanck** [comment]
This isn't quite fixed.  The program doesn't crash, but the output does not match the GUI based output.  There seems to be a terminal mode issue as well.  The readchar does not take any input until a newline is entered.  Using the sample code I provided, I have to type enter twice to leave the program in CLI mode. The ascii code of the chars typed are not printed in real-time as I enter them.  When using redirected input, only the ascii code of the 1st char is printed.

**Comment by jplanck** [comment]
Accidentally closed.
